### ISSUE TITLE
Solo-deployed CNode throws error: data/config/.archive/genesis-network.json: Device or resource busy

### ISSUE THREAD

**Issue by alex-kuzmin-hg** [hashgraph/solo#1027]
### Describe the bug

Solo-deployed CNode throws error:
hgcaa.log:2024-12-28 20:41:21.547 WARN  388  DiskStartupNetworks - Failed to archive [genesis-network.json]
hgcaa.log:java.nio.file.FileSystemException: data/config/genesis-network.json -> data/config/.archive/genesis-network.json: Device or resource busy

### Describe the expected behavior

hgcaa.log:2024-12-28 20:41:21.547 WARN  388  DiskStartupNetworks - Failed to archive [genesis-network.json]
hgcaa.log:java.nio.file.FileSystemException: data/config/genesis-network.json -> data/config/.archive/genesis-network.json: Device or resource busy
hgcaa.log-	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:100) ~[?:?]
hgcaa.log-	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106) ~[?:?]
hgcaa.log-	at java.base/sun.nio.fs.UnixFileSystem.move(UnixFileSystem.java:934) ~[?:?]
hgcaa.log-	at java.base/sun.nio.fs.UnixFileSystemProvider.move(UnixFileSystemProvider.java:309) ~[?:?]
hgcaa.log-	at java.base/java.nio.file.Files.move(Files.java:1430) ~[?:?]

### To Reproduce

use latest main branch of Solo.
deploy normally with the "task", e.g. hedera-services branch: 17171-override-weight-mgmt
CN will throw the error above

**Comment by alex-kuzmin-hg** [comment]
I'm investigating for more details...

**Comment by alex-kuzmin-hg** [comment]
Root cause:
the CN code tries to File.move() mounted resource:
`/dev/md0 on /opt/hgcapp/services-hedera/HapiApp2.0/data/config/genesis-network.json type ext4 (ro,relatime,stripe=256)
`

[https://github.com/hashgraph/hedera-services/blob/346ac6489173bf282245ad9768998a06[…]src/main/java/com/hedera/node/app/info/DiskStartupNetworks.java](https://github.com/hashgraph/hedera-services/blob/346ac6489173bf282245ad9768998a06dd9ed41a/hedera-node/hedera-app/src/main/java/com/hedera/node/app/info/DiskStartupNetworks.java#L145)

**Comment by alex-kuzmin-hg** [comment]
Introduced in https://github.com/hashgraph/hedera-services/pull/16594/files
