### ISSUE TITLE
Fix copyTo and copyFrom command in K8 class

### ISSUE THREAD

**Issue by leninmehedy** [hashgraph/solo#57]
I think the way to first try and solve this is by upgrading all of our tools to the latest version of Kuberenetes/Kubectl/Kind /etc so that it will leverage the websocket, which might seem to solve the problem.

```
K8 › should be able to copy a file to and from a container

    ZlibError: zlib: unexpected end of file

      at Unzip.write (node_modules/minizlib/index.js:154:22)
      at Unzip.flush (node_modules/minizlib/index.js:105:10)
      at Unzip.end (node_modules/minizlib/index.js:111:10)
      at Unpack.end (node_modules/tar/lib/parse.js:544:21)
      at Pipe.end (node_modules/fs-minipass/node_modules/minipass/index.js:75:17)
      at ReadStream.[emitEnd2] (node_modules/fs-minipass/node_modules/minipass/index.js:522:9)
      at ReadStream.[emitEnd] (node_modules/fs-minipass/node_modules/minipass/index.js:507:21)
      at ReadStream.emit (node_modules/fs-minipass/node_modules/minipass/index.js:458:27)
      at ReadStream.emit (node_modules/fs-minipass/index.js:175:22)
      at ReadStream.[maybeEmitEnd] (node_modules/fs-minipass/node_modules/minipass/index.js:440:12)
      at ReadStream.emit (node_modules/fs-minipass/node_modules/minipass/index.js:474:27)
      at ReadStream.emit (node_modules/fs-minipass/index.js:175:22)
      at ReadStream.[resume] (node_modules/fs-minipass/node_modules/minipass/index.js:312:10)
      at Unpack.Pipe.ondrain (node_modules/fs-minipass/node_modules/minipass/index.js:64:37)
      at ReadEntry.<anonymous> (node_modules/tar/lib/parse.js:439:47)
      at ReadEntry.emit (node_modules/tar/node_modules/minipass/index.js:498:23)
      at ReadEntry.[flush] (node_modules/tar/node_modules/minipass/index.js:378:62)
      at ReadEntry.[resume] (node_modules/tar/node_modules/minipass/index.js:337:41)
      at WriteStream.Pipe.ondrain (node_modules/tar/node_modules/minipass/index.js:74:37)
      at WriteStream.emit (node_modules/fs-minipass/index.js:257:18)
      at WriteStream.[_onwrite] (node_modules/fs-minipass/index.js:345:16)
      at node_modules/fs-minipass/index.js:325:21
```
- [ ] requires: https://github.com/hashgraph/solo/issues/503 (if we are going to do the upgrade to solve the problem)

**Comment by leninmehedy** [comment]
Remove `async`: https://github.com/hashgraph/solo/blob/f4f8527fc30eb8fe8d7900fdf57158119e2f0181/src/core/k8.mjs#L485C11-L488C14

It seems `tar` is probably failing to run when we are uploading a large file like build.zip (~90Mb)

**Comment by leninmehedy** [comment]
The error log in this ticket is confusing because `copyTo` and `copyFrom` doesn't use Zlib. However, we need to test thoroughly with a large file and find out why `copyTo` and `copyFrom` fails.

**Comment by matteriben** [comment]
This may have been fixed in the kubernetes 1.30 release (ga 4/17/24).
https://github.com/kubernetes/kubernetes/issues/60140#issuecomment-1986228775
https://www.kubernetes.dev/resources/release/

**Comment by jeromy-cannon** [comment]
A few more notes.  1.30+ is available.  I think we would need to update Kind version, update the readme, and also update the kubernetes node client.

We could also add retry logic, here is the source code of the Java libraries:
- https://github.com/kubernetes-client/javascript : src/web-socket-handler.ts
- https://github.com/kubernetes-client/javascript : src/exec.ts

**Comment by jeromy-cannon** [comment]
potential future solutions (if we need to reopen this ticket in the future):

1. tar the file first, then send the bytes back/down and decompress locally (current version is tar'ing with compression and piping to stdout, which feels the buffer and creates instability)
2. make a list of files, and do each one individually one at a time using the above #1 
3. add retry and resume logic (resume if multiple files)

**Comment by jeromy-cannon** [comment]
a different error, but copyFrom is failing more frequently
